# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: [deploy-to-qa1]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.event.client_payload.branch }}

    - name: Declare some variables
      id: vars
      env:
        DD: ${{ github.event.client_payload.branch }}
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${DD#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse HEAD)" 
        
    - uses: 8398a7/action-slack@v2
      with:
        status: custom
        payload: |
          {
            text: "Deployment",
            attachments: [{
              "author_name": "deploy-to-qa1", // json
              fallback: 'fallback',
              color: '#FFCC00',
              title: 'Status',
              text: 'STARTING',
              fields: [{
                title: 'Branch',
                value: `<https://github.com/nichesoftgh02/test/commit/${{ steps.vars.outputs.sha_short }} | ${{ github.event.client_payload.branch }}>`,
                short: false
              }],
              footer_icon: 'https://github.githubassets.com/favicon.ico',
              footer: `<https://github.com/nichesoftgh02/test | nichesoftgh02/test>`,
              ts: Math.floor(Date.now() / 1000),
              actions: [{
              }]
            }]
          }
      env:
        DD: ${{ github.event.client_payload.branch }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: success()
      
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    
    - name: Another step
      run: |
        echo "Branch: ${{ steps.vars.outputs.branch }}"
        echo "Sha: ${{ steps.vars.outputs.sha_short }}"
        BRANCH=$(echo $BRANCH | sed -e "s/refs\/heads\///")
        echo "Branch: $BRANCH"
        echo "Sha: $GITHUB_SHA"
    
    - uses: 8398a7/action-slack@v2
      with:
        status: custom
        payload: |
          {
            text: "Deployment",
            attachments: [{
              "author_name": "deploy-to-qa1", // json
              fallback: 'fallback',
              color: '#00ff00',
              title: 'Status',
              text: 'SUCCESS',
              fields: [{
                title: 'Branch',
                value: `<https://github.com/nichesoftgh02/test/commit/${{ steps.vars.outputs.sha_short }} | ${{ github.event.client_payload.branch }}>`,
                short: false
              }],
              footer_icon: 'https://github.githubassets.com/favicon.ico',
              footer: `<https://github.com/nichesoftgh02/test | nichesoftgh02/test>`,
              ts: Math.floor(Date.now() / 1000),
              actions: [{
              }]
            }]
          }
      env:
        DD: ${{ github.event.client_payload.branch }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: success()
      
    - uses: 8398a7/action-slack@v2
      with:
        status: custom
        payload: |
          {
            text: "Deployment",
            attachments: [{
              "author_name": "deploy-to-qa1", // json
              fallback: 'fallback',
              color: '#FF0000',
              title: 'Status',
              text: 'FAILED',
              fields: [{
                title: 'Branch',
                value: `<https://github.com/nichesoftgh02/test/commit/${{ steps.vars.outputs.sha_short }} | ${{ github.event.client_payload.branch }}>`,
                short: false
              }],
              footer_icon: 'https://github.githubassets.com/favicon.ico',
              footer: `<https://github.com/nichesoftgh02/test | nichesoftgh02/test>`,
              ts: Math.floor(Date.now() / 1000),
              actions: [{
              }]
            }]
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: failure()
      
