# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: [deploy-to-qa1]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.event.client_payload.branch }}

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Declare some variables
      id: vars
      env:
        DD: ${{ github.event.client_payload.branch }}
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${DD#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse HEAD)"

    - name: Another step
      run: |
        echo "Branch: ${{ steps.vars.outputs.branch }}"
        echo "Sha: ${{ steps.vars.outputs.sha_short }}"
        
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Integration Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
  
    - uses: 8398a7/action-slack@v2
      with:
        status: custom
        payload: |
          {
            text: "Custom Field Check",
            attachments: [{
              "author_name": "deploy-to-qa1", // json
              fallback: 'fallback',
              color: 'good',
              title: 'CI Result',
              text: `${{ github.event.client_payload.branch }}`,
              fields: [{
                title: 'Branch',
                value: `${{ github.event.client_payload.branch }}`,
                short: true
              },
              {
                title: 'Sha',
                value: `${{ steps.vars.outputs.sha_short }}`,
                short: true
              },
              {
                title: 'long title1',
                value: 'long value1',
                short: false
              }],
              actions: [{
              }]
            }]
          }
      env:
        DD: ${{ github.event.client_payload.branch }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
